<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="user" name="com.cogniphi.MuthootServillance.TestSuite.AttendanceSuite" tests="2" failures="1" timestamp="1 Sep 2018 10:20:37 GMT" time="112.750" errors="0">
  <testcase name="TC_0026_status" time="99.513" classname="com.cogniphi.MuthootServillance.TestSuite.AttendanceSuite">
    <failure type="java.lang.AssertionError" message="Attendance was not found on the web page">
      <![CDATA[java.lang.AssertionError: Attendance was not found on the web page
	at org.testng.Assert.fail(Assert.java:94)
	at UTILITY.SafeActions.click_on_the_field(SafeActions.java:67)
	at UTILITY.SafeActions.markAsperERTAndPerson(SafeActions.java:233)
	at com.cogniphi.MuthootServillance.AttendanceDetails.markPerson_For_All_erts(AttendanceDetails.java:318)
	at com.cogniphi.MuthootServillance.AttendanceDetails.markAttendanceForAllGuard(AttendanceDetails.java:359)
	at com.cogniphi.MuthootServillance.TestSuite.AttendanceSuite.TC_0026_status(AttendanceSuite.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_0026_status -->
  <testcase name="TC_001_verify_Attendance_DetailsPage" time="13.237" classname="com.cogniphi.MuthootServillance.TestSuite.AttendanceSuite"/>
</testsuite> <!-- com.cogniphi.MuthootServillance.TestSuite.AttendanceSuite -->
